name: CI (Maven)

on:
  push:
    branches: [main, feat/**, fix/**, chore/**]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      # Construye el módulo web desde la raíz del repo usando -f
      - name: Build with Maven
        run: mvn -B -ntp -f devjobs-servlets/pom.xml -DskipTests package

      # Sube el WAR como artefacto del build
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: devjobs-servlets-war
          path: devjobs-servlets/target/devjobs-servlets.war
